name: 'OData schema inspector'
description: 'OData schema inspector to detect breaking change and other dangerous changes.'
branding:
  icon: sliders
  color: purple
inputs:
  branch:
    description: 'Source branch.'
    required: true
  targetBranch:
    description: 'Target branch.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-b'
  - ${{ inputs.branch }}
  - '-t'
  - ${{ inputs.targetBranch }}
  - '-o'
  - ${{ inputs.repoOwner }}
  - '-n'
  - ${{ inputs.repoName }}
