name: 'OData schema inspector'
description: 'OData schema inspector to detect breaking change and other dangerous changes.'
branding:
  icon: sliders
  color: purple
inputs:
  branch:
    description: 'Source branch.'
    required: true
  targetBranch:
    description: 'Target branch.'
    required: true
outputs:
  summary-title:
    description: 'The title of the code metrics action.'
  summary-details:
    description: 'A detailed summary of all the projects that were flagged.'
  updated-metrics:
    description: 'A boolean value, indicating whether or not the CODE_METRICS.md was updated as a result of running this action.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-b'
  - ${{ inputs.owner }}
  - '-t'
  - ${{ inputs.name }}
